#include "action_repr.h"

#include "sc2api/sc2_api.h"
#include <map>
#include <vector>
#include "constants.h"

//#define DEBUG // Comment out to disable debug prints in this file.
#ifdef DEBUG
#include <iostream>
#define PRINT(s) std::cout << s << std::endl;
#define TEST(s) s
#else
#define PRINT(s)
#define TEST(s)
#endif // DEBUG

using sc2::UNIT_TYPEID;
using sc2::ABILITY_ID;

ActionRepr::ActionRepr(
    std::map<UNIT_TYPEID, int> const & required_,
    std::map<UNIT_TYPEID, int> const & consumed_,
    std::map<UNIT_TYPEID, int> const & borrowed_,
    std::map<UNIT_TYPEID, int> const & produced_,
    float time_) :
    required(required_),
    consumed(consumed_),
    borrowed(borrowed_),
    produced(produced_),
    time_required(time_)
{

}

std::map<ACTION, ActionRepr> ActionRepr::values = {
    //Resource gathering
    { ACTION::SCV_GATHER_MINERALS, ActionRepr({}, {{UNIT_FAKEID::TERRAN_SCV_VESPENE, 1}},{},{{ UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}}, 1.5) },
    { ACTION::SCV_GATHER_VESPENE, ActionRepr({{UNIT_TYPEID::TERRAN_REFINERY, 1}},{{ UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{},{{UNIT_FAKEID::TERRAN_SCV_VESPENE, 1}}, 1.5) },
    { ACTION::MULE_GATHER_MINERALS, ActionRepr({},{},{{UNIT_TYPEID::TERRAN_ORBITALCOMMAND, 1},{UNIT_FAKEID::TERRAN_MULE_VESPENE, -1}},{}, 64) },
    { ACTION::MULE_GATHER_VESPENE, ActionRepr({},{},{{UNIT_TYPEID::TERRAN_ORBITALCOMMAND, 1},{UNIT_FAKEID::TERRAN_MULE_MINERALS, -1}},{}, 64) },

    // Building construction
    { ACTION::BUILD_COMMAND_CENTER, ActionRepr({}, { { UNIT_FAKEID::MINERALS, 400 } }, { {UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}}, { {UNIT_TYPEID::TERRAN_COMMANDCENTER, 1}, {UNIT_FAKEID::TERRAN_ANY_COMMANDCENTER, 1}}, 71) },
    { ACTION::BUILD_PLANETARY_FORTRESS, ActionRepr({{UNIT_TYPEID::TERRAN_ENGINEERINGBAY, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 150}, {UNIT_TYPEID::TERRAN_COMMANDCENTER, 1}},{ { UNIT_FAKEID::TERRAN_ANY_COMMANDCENTER, 1 } },{{UNIT_TYPEID::TERRAN_PLANETARYFORTRESS, 1}}, 36) },
    { ACTION::BUILD_ORBITAL_COMMAND, ActionRepr({{UNIT_TYPEID::TERRAN_BARRACKS, 1}},{{UNIT_TYPEID::TERRAN_COMMANDCENTER, 1}, {UNIT_FAKEID::MINERALS, 150}},{{UNIT_FAKEID::TERRAN_ANY_COMMANDCENTER, 1}},{{UNIT_TYPEID::TERRAN_ORBITALCOMMAND, 1}}, 25) },
    { ACTION::BUILD_SUPPLY_DEPOT, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_SUPPLYDEPOT, 1}}, 21) },
    { ACTION::BUILD_REFINERY, ActionRepr({},{{UNIT_FAKEID::MINERALS, 75}, {UNIT_TYPEID::NEUTRAL_VESPENEGEYSER, 1}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_REFINERY, 1}}, 21) },
    { ACTION::BUILD_BARRACKS, ActionRepr({{UNIT_TYPEID::TERRAN_SUPPLYDEPOT, 1}},{{UNIT_FAKEID::MINERALS, 150}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_BARRACKS, 1}, {UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}}, 46) },
    { ACTION::BUILD_ENGINEERING_BAY, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_COMMANDCENTER, 1}},{{UNIT_FAKEID::MINERALS, 125}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_ENGINEERINGBAY, 1}}, 25) },
    { ACTION::BUILD_BUNKER, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_BUNKER, 1}}, 29) },
    { ACTION::BUILD_SENSOR_TOWER, ActionRepr({{UNIT_TYPEID::TERRAN_ENGINEERINGBAY, 1}},{{UNIT_FAKEID::MINERALS, 125}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}}, { {UNIT_TYPEID::TERRAN_SENSORTOWER, 1}}, 18) },
    { ACTION::BUILD_MISSILE_TURRET, ActionRepr({{UNIT_TYPEID::TERRAN_ENGINEERINGBAY, 1}},{{UNIT_FAKEID::MINERALS, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_MISSILETURRET, 1}}, 18) },
    { ACTION::BUILD_FACTORY, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_FACTORY, 1}, {UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}}, 43) },
    { ACTION::BUILD_GHOST_ACADEMY, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 50}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_GHOSTACADEMY, 1}}, 29) },
    { ACTION::BUILD_STARPORT, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_STARPORT, 1}, {UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}}, 36) },
    { ACTION::BUILD_ARMORY, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_ARMORY, 1}}, 46) },
    { ACTION::BUILD_FUSION_CORE, ActionRepr({{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 150}},{{UNIT_FAKEID::TERRAN_SCV_MINERALS, 1}},{{UNIT_TYPEID::TERRAN_FUSIONCORE, 1}}, 46) },
    { ACTION::BUILD_BARRACKS_TECH_LAB, ActionRepr({},{{UNIT_FAKEID::MINERALS, 50}, {UNIT_FAKEID::VESPENE, 25}, {UNIT_TYPEID::TERRAN_BARRACKS, 1}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_TYPEID::TERRAN_BARRACKSTECHLAB, 1}}, 18) },
    { ACTION::BUILD_FACTORY_TECH_LAB, ActionRepr({},{{UNIT_FAKEID::MINERALS, 50}, {UNIT_FAKEID::VESPENE, 25}, {UNIT_TYPEID::TERRAN_FACTORY, 1}},{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_TYPEID::TERRAN_FACTORYTECHLAB, 1}}, 18) },
    { ACTION::BUILD_STARPORT_TECH_LAB, ActionRepr({},{ { UNIT_FAKEID::MINERALS, 50 },{ UNIT_FAKEID::VESPENE, 25 },{ UNIT_TYPEID::TERRAN_STARPORT, 1 } },{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{ { UNIT_TYPEID::TERRAN_STARPORTTECHLAB, 1 } }, 18) },
    { ACTION::BUILD_BARRACKS_REACTOR, ActionRepr({},{{UNIT_FAKEID::MINERALS, 50}, {UNIT_FAKEID::VESPENE, 50}, {UNIT_TYPEID::TERRAN_BARRACKS, 1}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_TYPEID::TERRAN_BARRACKSREACTOR, 2}, {UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}}, 36) },
    { ACTION::BUILD_FACTORY_REACTOR, ActionRepr({},{ { UNIT_FAKEID::MINERALS, 50 },{ UNIT_FAKEID::VESPENE, 50 },{ UNIT_TYPEID::TERRAN_FACTORY, 1 } },{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{ { UNIT_TYPEID::TERRAN_FACTORYREACTOR, 2 }, {UNIT_FAKEID::TERRAN_ANY_FACTORY, 1} }, 36) },
    { ACTION::BUILD_STARPORT_REACTOR, ActionRepr({},{ { UNIT_FAKEID::MINERALS, 50 },{ UNIT_FAKEID::VESPENE, 50 },{ UNIT_TYPEID::TERRAN_STARPORT, 1 } },{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{ { UNIT_TYPEID::TERRAN_STARPORTREACTOR, 2 }, {UNIT_FAKEID::TERRAN_ANY_STARPORT, 1} }, 36) },
    
    // Unit training
    { ACTION::TRAIN_SCV, ActionRepr({},{ { UNIT_FAKEID::MINERALS, 50 } },{ { UNIT_FAKEID::TERRAN_ANY_COMMANDCENTER, 1 } },{ { UNIT_FAKEID::TERRAN_SCV_MINERALS, 1 } }, 12) },
    { ACTION::TRAIN_MARINE, ActionRepr({},{{UNIT_FAKEID::MINERALS, 50}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_TYPEID::TERRAN_MARINE, 1}}, 18) },
    { ACTION::TRAIN_REAPER, ActionRepr({},{{UNIT_FAKEID::MINERALS, 50}, {UNIT_FAKEID::VESPENE, 50}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}},{{UNIT_TYPEID::TERRAN_REAPER, 1}}, 32) },
    { ACTION::TRAIN_MARAUDER, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}, {UNIT_FAKEID::VESPENE, 25}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}, {UNIT_TYPEID::TERRAN_BARRACKSTECHLAB, 1}},{{UNIT_TYPEID::TERRAN_MARAUDER, 1}}, 21) },
    { ACTION::TRAIN_GHOST, ActionRepr({{UNIT_TYPEID::TERRAN_GHOSTACADEMY, 1}},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 125}},{{UNIT_TYPEID::TERRAN_BARRACKSTECHLAB, 1}},{{UNIT_FAKEID::TERRAN_ANY_BARRACKS, 1}}, 29) },
    { ACTION::TRAIN_HELLION, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}},{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_TYPEID::TERRAN_HELLION, 1}}, 21) },
    { ACTION::TRAIN_HELLBAT, ActionRepr({{UNIT_TYPEID::TERRAN_ARMORY, 1}},{{UNIT_FAKEID::MINERALS, 100}}, { {UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_TYPEID::TERRAN_HELLIONTANK, 1}}, 21) },
    { ACTION::TRAIN_WIDOW_MINE, ActionRepr({},{{UNIT_FAKEID::MINERALS, 75}, {UNIT_FAKEID::VESPENE, 25}},{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}, {UNIT_TYPEID::TERRAN_FACTORYREACTOR, 1}},{{UNIT_TYPEID::TERRAN_WIDOWMINE, 1}}, 29) },
    { ACTION::TRAIN_SIEGE_TANK, ActionRepr({},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 125}},{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}, {UNIT_TYPEID::TERRAN_FACTORYTECHLAB, 1}},{{UNIT_TYPEID::TERRAN_SIEGETANK, 1}}, 32) },
    { ACTION::TRAIN_CYCLONE, ActionRepr({},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_TYPEID::TERRAN_CYCLONE, 1}}, 32) },
    { ACTION::TRAIN_THOR, ActionRepr({},{{UNIT_FAKEID::MINERALS, 300}, {UNIT_FAKEID::VESPENE, 200}},{{UNIT_TYPEID::TERRAN_FACTORYTECHLAB, 1}, {UNIT_FAKEID::TERRAN_ANY_FACTORY, 1}},{{UNIT_TYPEID::TERRAN_THOR, 1}}, 43) },
    { ACTION::TRAIN_VIKING, ActionRepr({},{{UNIT_FAKEID::MINERALS,  150}, {UNIT_FAKEID::VESPENE, 75}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{{UNIT_TYPEID::TERRAN_VIKINGFIGHTER, 1}}, 30) },
    { ACTION::TRAIN_MEDIVAC, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{{UNIT_TYPEID::TERRAN_MEDIVAC, 1}}, 30) },
    { ACTION::TRAIN_LIBERATOR, ActionRepr({},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 150}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{{UNIT_TYPEID::TERRAN_LIBERATOR, 1}}, 43) },
    { ACTION::TRAIN_RAVEN, ActionRepr({},{{UNIT_FAKEID::MINERALS, 100}, {UNIT_FAKEID::VESPENE, 200}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}},{{UNIT_TYPEID::TERRAN_RAVEN, 1}}, 43) },
    { ACTION::TRAIN_BANSHEE, ActionRepr({},{{UNIT_FAKEID::MINERALS, 150}, {UNIT_FAKEID::VESPENE, 100}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}, {UNIT_TYPEID::TERRAN_STARPORTTECHLAB, 1}},{{UNIT_TYPEID::TERRAN_BANSHEE, 1}}, 43) },
    { ACTION::TRAIN_BATTLECRUISER, ActionRepr({{UNIT_TYPEID::TERRAN_FUSIONCORE, 1}},{{UNIT_FAKEID::MINERALS, 400}, {UNIT_FAKEID::VESPENE, 300}},{{UNIT_FAKEID::TERRAN_ANY_STARPORT, 1}, {UNIT_TYPEID::TERRAN_STARPORTTECHLAB, 1}},{{UNIT_TYPEID::TERRAN_BATTLECRUISER, 1}}, 64) },
    { ACTION::TRAIN_POINT_DEFENSE_DRONE, ActionRepr({},{},{{UNIT_TYPEID::TERRAN_RAVEN, 1}},{{UNIT_TYPEID::TERRAN_POINTDEFENSEDRONE, 1}}, 1) }, // TODO: Energy cost. Time might not be accurate.
    { ACTION::TRAIN_AUTO_TURRET, ActionRepr({},{},{{UNIT_TYPEID::TERRAN_RAVEN, 1}},{{UNIT_TYPEID::TERRAN_AUTOTURRET, 1}}, 1) }, // TODO: Energy cost. Time might not be accurate.

    // Research

    // Other
};

std::map<ACTION, ABILITY_ID> ActionRepr::convert_our_api = {};
std::map<ABILITY_ID, ACTION> ActionRepr::convert_api_our = {};

void ActionRepr::InitConvertMap() {
}

#undef DEBUG
#undef PRINT
#undef TEST
