#pragma once

#include <sc2api/sc2_api.h>
#include <map>

std::map<sc2::UNIT_TYPEID, std::vector<sc2::UNIT_TYPEID>> zerg_countertable = {
    { sc2::UNIT_TYPEID::ZERG_ZERGLING, {sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_MARINE} }, //MARINE WITH SUPPORT AND UPGRADES
    { sc2::UNIT_TYPEID::ZERG_ROACH, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_THOR} }, //THOR WITH +3 WEAPONS
    { sc2::UNIT_TYPEID::ZERG_HYDRALISK, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_HELLION} }, //BE CAREFUL WITH BATTLECRUISER
    { sc2::UNIT_TYPEID::ZERG_MUTALISK, {sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_MARINE } },
    { sc2::UNIT_TYPEID::ZERG_CORRUPTOR, {sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARINE} },
    { sc2::UNIT_TYPEID::ZERG_INFESTOR, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_GHOST} },
    { sc2::UNIT_TYPEID::ZERG_ULTRALISK, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_MARAUDER} },
    { sc2::UNIT_TYPEID::ZERG_BANELING, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_WIDOWMINE, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARAUDER} },
    { sc2::UNIT_TYPEID::ZERG_BROODLORD, {sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER} },
    { sc2::UNIT_TYPEID::ZERG_QUEEN, {sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK} },
    { sc2::UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER} }, //MARAUDERS IN MEDIVACS
    { sc2::UNIT_TYPEID::ZERG_SWARMHOSTMP, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER} }, //MARAUDERS IN MEDIVACS
    { sc2::UNIT_TYPEID::ZERG_VIPER, {sc2::UNIT_TYPEID::TERRAN_GHOST} }
};

std::map<sc2::UNIT_TYPEID, std::vector<sc2::UNIT_TYPEID>> protoss_countertable = {
    { sc2::UNIT_TYPEID::PROTOSS_ZEALOT,{ sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK } },
    { sc2::UNIT_TYPEID::PROTOSS_SENTRY,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_BANSHEE} }, 
    { sc2::UNIT_TYPEID::PROTOSS_STALKER,{ sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_HELLION } }, 
    { sc2::UNIT_TYPEID::PROTOSS_IMMORTAL,{ sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_GHOST, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_RAVEN, sc2::UNIT_TYPEID::TERRAN_WIDOWMINE} },
    { sc2::UNIT_TYPEID::PROTOSS_COLOSSUS,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK} },
    { sc2::UNIT_TYPEID::PROTOSS_VOIDRAY,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_MARINE } },
    { sc2::UNIT_TYPEID::PROTOSS_PHOENIX,{ sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_THOR} },
    { sc2::UNIT_TYPEID::PROTOSS_CARRIER,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER} },
    { sc2::UNIT_TYPEID::PROTOSS_MOTHERSHIP,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER} },
    { sc2::UNIT_TYPEID::PROTOSS_MOTHERSHIPCORE,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER } },
    { sc2::UNIT_TYPEID::PROTOSS_WARPPRISM,{ sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_THOR} },
    { sc2::UNIT_TYPEID::PROTOSS_HIGHTEMPLAR,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_GHOST} }, 
    { sc2::UNIT_TYPEID::PROTOSS_DARKTEMPLAR,{ sc2::UNIT_TYPEID::TERRAN_BANSHEE} }, 
    { sc2::UNIT_TYPEID::PROTOSS_ARCHON,{ sc2::UNIT_TYPEID::TERRAN_GHOST, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER } }, //ghost EMP
    { sc2::UNIT_TYPEID::PROTOSS_ORACLE, { sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_MISSILETURRET}},
    { sc2::UNIT_TYPEID::PROTOSS_TEMPEST, { sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER}}
};

std::map<sc2::UNIT_TYPEID, std::vector<sc2::UNIT_TYPEID>> terran_countertable = {
    { sc2::UNIT_TYPEID::TERRAN_MARINE,{ sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER } },
    { sc2::UNIT_TYPEID::TERRAN_MARAUDER,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_BANSHEE } },
    { sc2::UNIT_TYPEID::TERRAN_REAPER,{ sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_HELLION} },
    { sc2::UNIT_TYPEID::TERRAN_GHOST,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_GHOST, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER} },
    { sc2::UNIT_TYPEID::TERRAN_HELLION,{ sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_THOR } },
    { sc2::UNIT_TYPEID::TERRAN_SIEGETANK,{ sc2::UNIT_TYPEID::TERRAN_BANSHEE} },
    { sc2::UNIT_TYPEID::TERRAN_THOR,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER} },
    { sc2::UNIT_TYPEID::TERRAN_BANSHEE,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_THOR } },
    { sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_MARINE } },
    { sc2::UNIT_TYPEID::TERRAN_RAVEN,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_GHOST } },
    { sc2::UNIT_TYPEID::TERRAN_MEDIVAC,{ sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER, sc2::UNIT_TYPEID::TERRAN_THOR } },
    { sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER,{ sc2::UNIT_TYPEID::TERRAN_VIKINGFIGHTER} },
    { sc2::UNIT_TYPEID::TERRAN_HELLIONTANK,{ sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_THOR } },
    { sc2::UNIT_TYPEID::TERRAN_WIDOWMINE,{ sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_THOR} },
};
