#pragma once

#include <sc2api/sc2_api.h>
#include <unordered_map>


/*
std::unordered_map<sc2::UNIT_TYPEID, std::tuple<sc2::UNIT_TYPEID>> zerg_countertable = {
    {sc2::UNIT_TYPEID::ZERG_ZERGLING, (sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS, sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK) }, //MARINE WITH SUPPORT AND UPGRADES
    {sc2::UNIT_TYPEID::ZERG_ROACH, (sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_THOR) }, //THOR WITH +3 WEAPONS
    {sc2::UNIT_TYPEID::ZERG_HYDRALISK, (sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK) }, //BE CAREFUL WITH BATTLECRUISER
    {sc2::UNIT_TYPEID::ZERG_MUTALISK, (sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER) },
    {sc2::UNIT_TYPEID::ZERG_CORRUPTOR, (sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARINE) },
    {sc2::UNIT_TYPEID::ZERG_INFESTOR, (sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_GHOST) },
    {sc2::UNIT_TYPEID::ZERG_ULTRALISK, (sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_MARAUDER) },
    {sc2::UNIT_TYPEID::ZERG_BANELING, (sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_WIDOWMINE, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARAUDER) },
    {sc2::UNIT_TYPEID::ZERG_BROODLORD, (sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER) },
    {sc2::UNIT_TYPEID::ZERG_QUEEN, (sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK) },
    {sc2::UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP, (sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER) }, //MARAUDERS IN MEDIVACS
    {sc2::UNIT_TYPEID::ZERG_SWARMHOSTMP, (sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER) }, //MARAUDERS IN MEDIVACS
    {sc2::UNIT_TYPEID::ZERG_VIPER, (sc2::UNIT_TYPEID::TERRAN_GHOST) }
};
*/
std::unordered_map<sc2::UNIT_TYPEID, std::vector<sc2::UNIT_TYPEID>> zerg_countertable = {
    { sc2::UNIT_TYPEID::ZERG_ZERGLING, {sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK, sc2::UNIT_TYPEID::TERRAN_MARINE} }, //MARINE WITH SUPPORT AND UPGRADES
    { sc2::UNIT_TYPEID::ZERG_ROACH, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_THOR} }, //THOR WITH +3 WEAPONS
    { sc2::UNIT_TYPEID::ZERG_HYDRALISK, {sc2::UNIT_TYPEID::TERRAN_HELLION, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK} }, //BE CAREFUL WITH BATTLECRUISER
    { sc2::UNIT_TYPEID::ZERG_MUTALISK, {sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER} },
    { sc2::UNIT_TYPEID::ZERG_CORRUPTOR, {sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARINE} },
    { sc2::UNIT_TYPEID::ZERG_INFESTOR, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_GHOST} },
    { sc2::UNIT_TYPEID::ZERG_ULTRALISK, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_MARAUDER} },
    { sc2::UNIT_TYPEID::ZERG_BANELING, {sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_WIDOWMINE, sc2::UNIT_TYPEID::TERRAN_THOR, sc2::UNIT_TYPEID::TERRAN_MARAUDER} },
    { sc2::UNIT_TYPEID::ZERG_BROODLORD, {sc2::UNIT_TYPEID::TERRAN_VIKINGASSAULT, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER} },
    { sc2::UNIT_TYPEID::ZERG_QUEEN, {sc2::UNIT_TYPEID::TERRAN_MARINE, sc2::UNIT_TYPEID::TERRAN_MARAUDER, sc2::UNIT_TYPEID::TERRAN_HELLIONTANK} },
    { sc2::UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER} }, //MARAUDERS IN MEDIVACS
    { sc2::UNIT_TYPEID::ZERG_SWARMHOSTMP, {sc2::UNIT_TYPEID::TERRAN_BANSHEE, sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER, sc2::UNIT_TYPEID::TERRAN_SIEGETANK, sc2::UNIT_TYPEID::TERRAN_MARAUDER} }, //MARAUDERS IN MEDIVACS
    { sc2::UNIT_TYPEID::ZERG_VIPER, {sc2::UNIT_TYPEID::TERRAN_GHOST} }
};