#include "countertable.h"

using namespace sc2;
using namespace std;

std::unordered_map<UNIT_TYPEID, tuple<UNIT_TYPEID>> zerg_countertable = {
    {UNIT_TYPEID::ZERG_ZERGLING, (UNIT_TYPEID::TERRAN_HELLION, UNIT_TYPEID::TERRAN_PLANETARYFORTRESS, UNIT_TYPEID::TERRAN_MARINE, UNIT_TYPEID::TERRAN_HELLIONTANK)}, //MARINE WITH SUPPORT AND UPGRADES
    {UNIT_TYPEID::ZERG_ROACH, (UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_MARAUDER, UNIT_TYPEID::TERRAN_THOR)}, //THOR WITH +3 WEAPONS
    {UNIT_TYPEID::ZERG_HYDRALISK, (UNIT_TYPEID::TERRAN_HELLION, UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_BATTLECRUISER, UNIT_TYPEID::terran_carrier, UNIT_TYPEID::TERRAN_HELLIONTANK)}, //BE CAREFUL WITH BATTLECRUISER
    {UNIT_TYPEID::ZERG_MUTALISK, (UNIT_TYPEID::TERRAN_THOR, UNIT_TYPEID::TERRAN_MARINE, UNIT_TYPEID::TERRAN_BATTLECRUISER)},
    {UNIT_TYPEID::ZERG_CORRUPTOR, (UNIT_TYPEID::TERRAN_VIKINGASSAULT, UNIT_TYPEID::TERRAN_THOR, UNIT_TYPEID::TERRAN_MARINE)},
    {UNIT_TYPEID::ZERG_INFESTOR, (UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_GHOST)},
    {UNIT_TYPEID::ZERG_ULTRALISK, (UNIT_TYPEID::TERRAN_BANSHEE, UNIT_TYPEID::TERRAN_BATTLECRUISER, UNIT_TYPEID::TERRAN_MARAUDER)},
    {UNIT_TYPEID::ZERG_BANELING, (UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_WIDOWMINE, UNIT_TYPEID::TERRAN_THOR, UNIT_TYPEID::TERRAN_MARAUDER)},
    {UNIT_TYPEID::ZERG_BROODLORD, (UNIT_TYPEID::TERRAN_VIKINGASSAULT, UNIT_TYPEID::TERRAN_BATTLECRUISER)},
    {UNIT_TYPEID::ZERG_QUEEN, (UNIT_TYPEID::TERRAN_MARINE, UNIT_TYPEID::TERRAN_MARAUDER, UNIT_TYPEID::TERRAN_HELLIONTANK)},
    {UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP, (UNIT_TYPEID::TERRAN_BANSHEE, UNIT_TYPEID::TERRAN_BATTLECRUISER, UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_MARAUDER)}, //MARAUDERS IN MEDIVACS
    {UNIT_TYPEID::ZERG_SWARMHOSTMP, (UNIT_TYPEID::TERRAN_BANSHEE, UNIT_TYPEID::TERRAN_BATTLECRUISER, UNIT_TYPEID::TERRAN_SIEGETANK, UNIT_TYPEID::TERRAN_MARAUDER)}, //MARAUDERS IN MEDIVACS
    {UNIT_TYPEID::ZERG_VIPER, (UNIT_TYPEID::TERRAN_GHOST)}
}